version: "3"
services:
  spigot:
    build:
      context: .
      args:
        - SPIGOT_REV=${SPIGOT_REV}
        - JAVA_XMX=${JAVA_XMX}
        - JAVA_XMS=${JAVA_XMS}
      dockerfile: Dockerfile
    volumes:
      - ./data:/spigot_server
    container_name: "spigot"
    restart: always
    ports:
      - 25565:25565
    environment:
      SPIGOT_REV: ${SPIGOT_REV}
      JAVA_XMX: ${JAVA_XMX}
      JAVA_XMS: ${JAVA_XMS}